name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PNPM
        run: npm i -g pnpm    

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js app
        run: pnpm build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            # Load NVM and use Node.js v24
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 24

            echo "Using Node: $(node -v)"
            echo "Using NPM: $(npm -v)"

            # Ensure pnpm is installed
            if ! command -v pnpm &> /dev/null; then
              echo "pnpm not found, installing..."
              npm install -g pnpm
            fi

            # Ensure pm2 is installed
            if ! command -v pm2 &> /dev/null; then
              echo "pm2 not found, installing..."
              npm install -g pm2
            fi

            # Set project directory
            PROJECT_DIR="$HOME/admin"
            mkdir -p $PROJECT_DIR

            # Clone repository if it doesn’t exist, otherwise pull updates
            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "Repository not found. Cloning..."
              git clone https://github.com/Tevin0409/hikdigitalmart_admin.git $PROJECT_DIR
            else
              echo "Repository exists. Pulling latest changes..."
              cd $PROJECT_DIR
              git pull origin main
            fi

            # Navigate to project directory
            cd $PROJECT_DIR

            # Install dependencies using pnpm
            pnpm install --frozen-lockfile

            # Build the Next.js app
            pnpm build

            # Restart the application using PM2 on port 5000
            pm2 restart hikdigitalmart_admin || pm2 start pnpm --name "hikdigitalmart_admin" -- start -- -p 5000
